src/css/main.css, src/database/careerList.js, src/html/careers.html, src/html/careers/frontend.html, src/html/contribute.html, src/index.html, src/js/careerPage.js, src/js/homepage.js
Created a database folder and added the .js file that contains all the details of career paths that are available or coming soon. saving them as objects in an array.
Removed the data from the home page and careers page and imported them from the data base using JavaScript modules.
=> Created database

README.md
- I added links to the corresponding sections of the README.md file, based on their respective 'heading 2' anchor tags.
=> Add Table of Content (Task 1)

src/html/careers/frontend.html
**Reference Issues**
Closes #13 
**What does this implement/fix? Explain your changes.**
Added JavaScript article about "Knowing difference between var, let and const ~ Freecodecamp"
Article link - https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/
=> Added JavaScript article about knowing the difference between var, let and const.

README.md
- I created a `Back to Top` link at the end of every major section
- This pull request closes #8
=> Add 'Back to Top' link

src/html/careers/frontend.html
community section added with side-bar nav link.
=> Add Community section

src/html/careers/backend.html, src/html/careers/frontend.html, src/html/contribute.html
- Created a page for the Backend Career Roadmap which contains information about backend web development and links to useful resources on programming with Python, Mysql, as well as creating and utilizing APIs and Databases
- Moved the Back end card link up the list.
- Made corrections in the Backend career roadmap and corrected links to normalize.css across the website
(What Roadmap did you work on)
Backend roadmap
(Describe how this update/changes were implemented)
I copied the layout from the frontend roadmap and used it as a base layout. I updated the Side navigation to reflect the correct links
I added links to relevant resources and content
=> backendRoadmap

src/html/careers.html
I added two videos about a collection of **no-code careers** in tech:
- https://youtu.be/0_fuiK3b9OA
- https://youtu.be/c8oLHzW2qFU
=> Add two videos about no-code careers

src/html/careers/frontend.html
This was the video added: https://youtu.be/M44nEyd_5To
This is my second contribution to any project, so please give me your feedback on how I can bring perfection and get to work on the project.
=> added the link for bitbucket resource by atlassian

src/html/careers.html
the two videos I added are
1. https://youtu.be/AJsdLnsEFPQ
2. https://youtu.be/29ZJ4lN0PJY
=> task #3 in career in tech

src/html/careers.html
I've added two articles to the career page
1. https://www.business.com/articles/best-careers-tech-geeks/
2. https://www.freecodecamp.org/news/how-to-choose-the-best-tech-career-path-for-you-61c4d5ff9a77/
=> updated articles in career page

src/html/careers/backend.html
(What Roadmap did you work on)
Backend roadmap
(Describe how this update/changes were implemented)
=> backend roadmap

src/components/frontendPageContent/DesignResources.js, src/components/frontendPageContent/JsBasics.js
Reference Issues
Closes https://github.com/Timonwa/techroadmap/issues/15
What does this implement/fix?
1. Added Javascript tips and tricks, tools, cool examples etc -> [Codepen](https://codepen.io/) - The best place to build, test, and discover front-end code.
2. Added Design Resources tips and tricks, tools, cool examples etc -> [Fontello](https://fontello.com/) - icon fonts generator
=> added links frontend development page: javascript and design resources

src/components/backendPageContent/BackendNav.js, src/components/backendPageContent/Database.js
PostgreSQL with link to website, 2 tutorial videos for beginners, and 2 build-along projects, 1 project using node.js and PostgreSQL the other using python PostgreSQL and Heroku for hosting.
This pull request is in regards to Issue #56
=> Added new Database Language. Relational Database PostgreSQL

src/components/backendPageContent/BackendNav.js, src/components/backendPageContent/Database.js
This pull request is for issue #56 [FEATURE] Add more Database Languages.
Added Resource Card 'Microsoft SQL Server' and 5 resource links along with it to Database.js. 
Added SideBarSubtitle 'Microsoft SQL Server' with link to https://www.techroadmap.xyz/backend#microsoftsqlserver to BackendNav.js.
=> Added New Relational Database Language 'Microsoft SQL Server'

src/components/backendPageContent/BackendNav.js, src/components/backendPageContent/Database.js
Pull request is for Issue #56 Add more Database Language
Added 'Oracle' Resource Card with 5 resources to Database.js. 
Added Oracle SideBarSubtitle a href tag for Oracle section in BackendNav.js
=> Added Oracle to Relational Database Language

components/frontendPageContent/HtmlAndCssAdvanced.js
- Added https://www.simplilearn.com/tutorials/css-tutorial/advanced-css, an advanced CSS tutorial article (that also comes with a video) by Aryan Gupta from Simplilearn. 
- This is for the second task in #15
=> Add article resource to Advanced HTML and CSS section

components/backendPageContent/BackendLangs.js, components/backendPageContent/BackendNav.js
I have added resources to C# language.
=>  Added C# Resources

components/Networking.js, components/VersionControl.js, components/frontendPageContent/Apis.js, components/frontendPageContent/DeploymentServices.js, components/frontendPageContent/DesignResources.js, components/frontendPageContent/HtmlAndCssBasic.js, components/frontendPageContent/Intro.js, components/frontendPageContent/JsAdvanced.js, components/frontendPageContent/JsBasics.js, components/frontendPageContent/OtherResources.js, components/frontendPageContent/Roadmap.js, components/frontendPageContent/WhatIs.js, components/frontendPageContent/WhatNext.js
I fixed some typo errors and also updated part of the front-end page.
Though I still have concerns about the writing style ie to use `frontend` or `front-end`
=> Typo fixes

components/backendPageContent/CodeEditors.js
#75 Corrected the Styling for Subheader **Code Editor** in list of Mobile Apps in Backend Development Roadmap
Before
After
=> Corrected the Styling of Subheader *Code Editor* in listed Items 

components/frontendPageContent/HtmlAndCssAdvanced.js
#76 Styled the tools badge in HTML and CSS advanced section in frontend page
Before
After
=> Styled the tools badge in Frontend Page

styles/styled-components/SideBarLinks.styled.js
=> added a slightly light hover effect on hover of link in sideBar menu

components/frontendPageContent/JsFrameworks.js
Added a popular interactive React course from Scrimba. 
Issue #15
=> Add React front-end course link

components/frontendPageContent/Apis.js, components/frontendPageContent/CssFrameworks.js, components/frontendPageContent/HtmlAndCssAdvanced.js
~ add new api tools
~ add new htmlandCssAdvanced tool
~ add new Chakra ui tool for the cssFrameworks section
=> feat:add new frontend resources

components/backendPageContent/BackendNav.js, components/backendPageContent/Database.js
=> Added more database languages

components/frontendPageContent/JsBasics.js, yarn.lock
would love to contribute more to this project, as I like it. Thanks.
=> added new articles for Javascript Basics in Frontend Track

components/frontendPageContent/JsBasics.js
Added the following resources maintaining the coding style guidelines.
1. Javascript Debugging guide from Google
https://developer.chrome.com/docs/devtools/javascript 
2. Javascript pro tips from Fireship Youtube channel
https://youtu.be/Mus_vwhTCq0?si=8qXGfT5ONeIO4wFM
=> Added resources to Javascript basics others section

components/frontendPageContent/HtmlAndCssBasic.js
Hey I have added some useful articles on css.
This PR closes issue#128.
please review my PR. Thank you
=> Added two articles on CSS in the HtmlAndCssBasic.js file

components/backendPageContent/BackendLangs.js
I have added articles on C in the BackendLang.js file.
This PR closes issue #143
=> Added articles on C in the Backend Dev section
